apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
    team: {{ .Values.team }}
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      team: {{ .Values.team }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        team: {{ .Values.team }}
    spec:
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          name: {{ .Values.appName }}
          env:
          {{- if ((.Values.environmentVars)) }}
          {{- range $key, $value := .Values.environmentVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}

      
