apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
      name: http
  selector:
  app: {{ .Values.appName }}
