apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: nginx-demo/nonprod/v2
    cyclops-ui.com/write-repo: https://github.com/packituz-gttz/chart-demo
    cyclops-ui.com/write-revision: master
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: nginx-demo-nonprod-v2
  name: nginx-demo-v2
spec:
  targetNamespace: default
  template:
    path: chart
    repo: https://github.com/packituz-gttz/chart-demo
    version: master
  helm:
    valueFiles:
      - values.yaml
status:
  iconURL: ""
  managedGVRs: null
  reconciliationStatus:
    errors: null
  templateResolvedVersion: ""
