apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: nginx-demo-v3/templates/
    cyclops-ui.com/write-repo: https://github.com/packituz-gttz/chart-demo
    cyclops-ui.com/write-revision: master
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: nginx-demo3
  name: nginx-demo-v4
spec:
  targetNamespace: default
  template:
    path: chart
    repo: https://github.com/packituz-gttz/chart-demo
    sourceType: git
    version: master
  values:
    appName: my-app
    favourite: false
    global: {}
    image:
      name: nginx
      tag: latest
    replicas: 4
    team: marketing
status:
  iconURL: https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/static/img/default-template-icon.png?raw=true
  templateResolvedVersion: 612ad8ae12f09c94c7eda4f08cd6a919ad16e387
