apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: gitops-demo1
    cyclops-ui.com/write-repo: https://github.com/packituz-gttz/chart-demo
    cyclops-ui.com/write-revision: master
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: app
  name: demo-module1
  namespace: cyclops
spec:
  targetNamespace: default
  template:
    path: chart
    repo: https://github.com/packituz-gttz/chart-demo
    sourceType: git
    version: master
  values:
    appName: demo-m1
    environmentVars: {}
    favourite: false
    replicas: 10
    team: marketing
