apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: nginx-v1
    cyclops-ui.com/write-repo: https://github.com/packituz-gttz/chart-demo
    cyclops-ui.com/write-revision: master
    cyclops/reconciled-at: "2024-12-18T18:24:02Z"
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: nginx-demo
  name: nginx-v1
spec:
  targetNamespace: guestbook
  template:
    path: chart
    repo: https://github.com/packituz-gttz/chart-demo
    version: master
  values:
    appName: nginx1
    environmentVars: {}
    favourite: true
    replicas: 2
    team: sales
status:
  iconURL: ""
  managedGVRs: null
  reconciliationStatus:
    errors: null
  templateResolvedVersion: ""
