apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: nginx-v2
    cyclops-ui.com/write-repo: https://github.com/packituz-gttz/chart-demo
    cyclops-ui.com/write-revision: master
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: nginx2
  name: nginx-v2
spec:
  targetNamespace: guestbook
  template:
    path: chart
    repo: https://github.com/packituz-gttz/chart-demo
    version: master
  values:
    appName: nginx2
    environmentVars:
      OS: linux
    favourite: true
    replicas: 12
    team: genai
status:
  iconURL: ""
  managedGVRs: null
  reconciliationStatus:
    errors: null
  templateResolvedVersion: ""
